name: EMSR
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - numpy=1.23
  - scipy=1.10
  - h5py=3.8
  - pillow=9.4
  - pyyaml=6.0
  - matplotlib=3.7
  - tqdm
  - tensorboard
  - pytorch=1.13.1
  - torchvision=0.14.1
  - cudatoolkit=11.7   
  - pip
  - pip:
      - einops==0.6.1
      - timm==0.6.13
